from os import path

APPLICATION_NAME = ""
APPLICATION_ROOTDIR = "links"
APPLICATION_ROOT = path.sep + APPLICATION_ROOTDIR + path.sep
APPLICATION_MAPPERDIR = "mappers"

MODEL_STRING = "model"
CLUSTER_ID_STRING = "clusterId"
PROJECT_ID_STRING = "projectId"
OPTIONS_STRING = "options"
JS_URL_STRING = "jsUrl"

NAME_STRING = "name"
NAMES_STRING = "names"
SEARCH_STRING = "search"

URL_WILDCARD = "&"

RANCHER_KEY_CURRENT_CIS_RUN_NAME = "currentCisRunName"
RANCHER_KEY_DATA = "data"
RANCHER_KEY_ETCD_BACK_ID = "etcdBackupId"
RANCHER_KEY_FAILURES_ONLY = "failuresOnly"
RANCHER_KEY_ID = "id"
RANCHER_KEY_NAME = "name"
RANCHER_KEY_SKIP = "skip"
RANCHER_KEY_STATE = "state"
RANCHER_KEY_CLUSTER_TEMPLATE_NAME = "clusterTemplateName"
RANCHER_KEY_CLUSTER_TEMPLATE_ID = "clusterTemplateId"
RANCHER_KEY_CLUSTER_TEMPLATE_REVISION_NAME = "clusterTemplateRevisionName"

RANCHER_STATE_ACTIVE = "active"
RANCHER_STATE_UPDATING = "updating"

RANCHER_CLUSTER_TEMPLATE_REVISION_DEFAULT = "v1"
